import os

AZURE_OPENAI_GPT_API_KEY = os.getenv("AZURE_OPENAI_GPT_API_KEY")
AZURE_OPENAI_GPT_ENDPOINT = os.getenv("AZURE_OPENAI_GPT_ENDPOINT")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_GPT_CHAT_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_GPT_CHAT_DEPLOYMENT_NAME")

AZURE_OPENAI_GPT_4o_API_KEY = os.getenv("AZURE_OPENAI_GPT_4o_API_KEY")
AZURE_OPENAI_GPT_4o_ENDPOINT = os.getenv("AZURE_OPENAI_GPT_4o_ENDPOINT")
AZURE_OPENAI_GPT_4o_API_VERSION = os.getenv("AZURE_OPENAI_GPT_4o_API_VERSION")
AZURE_OPENAI_GPT_4o_CHAT_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_GPT_4o_CHAT_DEPLOYMENT_NAME")

