import os

AZURE_OPENAI_GPT_API_KEY = os.getenv("AZURE_OPENAI_GPT_API_KEY")
AZURE_OPENAI_GPT_ENDPOINT = os.getenv("AZURE_OPENAI_GPT_ENDPOINT")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_GPT_CHAT_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_GPT_CHAT_DEPLOYMENT_NAME")
AZURE_OPENAI_GPT_4_o_Mini_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_GPT_4_o_Mini_DEPLOYMENT_NAME")
AZURE_STORAGE_ACCOUNT_NAME = os.getenv("AZURE_STORAGE_ACCOUNT_NAME")
AZURE_STORAGE_CONTAINER_NAME = os.getenv("AZURE_STORAGE_CONTAINER_NAME")
AZURE_STORAGE_SAS_TOKEN = os.getenv("AZURE_STORAGE_SAS_TOKEN")
AZURE_COSMOS_PRIMARY_CONNECTION_STRING = os.getenv("AZURE_COSMOS_PRIMARY_CONNECTION_STRING")
AZURE_COSMOS_DATABASE_NAME = os.getenv("AZURE_COSMOS_DATABASE_NAME")
AZURE_COSMOS_CONTAINER_NAME = os.getenv("AZURE_COSMOS_CONTAINER_NAME")