rag_query = {
    'board_members_remuneration': """
        Find information about the remuneration details for board members. Specifically, I am looking for details on:
        1. The name of each board member.
        2. The commission earned by the board member.
        3. Sitting fees received for attending meetings.
        4. The salary of the board member.
        5. Details of benefits, perquisites, and allowances received by the board member.
        6. Information about Employee Stock Purchase Scheme (ESPS) details, if provided.
        7. The currency in which the remuneration is provided.
    """,
    'gender_diversity': """
        Provide details on the Gender Diversity of the board members, including the number of male and female members,
        and any policies or initiatives in place. Note that this information is present in the Corporate Governance section of the annual report.
    """,
    'board_member_details': """
        Please extract comprehensive information about the board members from the document. Specifically, I need:

        1. **Names**: The full names of each board member.
        2. **Designations/Roles**: The specific designations or roles (e.g., CEO, CFO, Independent Director, Non-Executive Director).
        3. **Membership Type**: The type of membership, categorized as:
          - Non-Independent, Executive Director
          - Non-Independent, Non-Executive Director
          - Independent, Non-Executive Director
        4. **Age**: The current age of each board member (if available).
        5. **Areas of Expertise**: Key areas of expertise for each board member, such as financial, leadership, IT, cybersecurity, etc.
        6. **Committees**: The committees each board member is part of, including audit, governance, or other specific committees.
        7. **Director Identification Number (DIN)**: The Director Identification Number, if available.
        8. **Gender**: The gender of each board member.
        9. **Tenure**: The tenure of each board member on the board.

        Please focus on returning document chunks that contain all available details for each board member mentioned above, 
        including additional relevant professional and biographical information.
    """,
    'carbon_emission_management': """
        Find information about the company's carbon emissions management strategies and performance. 
        I am particularly interested in:

        1. Scope 1 emissions (direct emissions from owned or controlled sources) in metric tons of CO2-equivalent.
        2. Scope 2 emissions (indirect emissions from purchased electricity, steam, heating, and cooling) in metric tons of CO2-equivalent.
        3. Scope 3 emissions (all other indirect emissions not covered in Scope 2) in metric tons of CO2-equivalent.
        4. The company's carbon reduction targets and progress towards achieving them.
        5. Any carbon offset initiatives the company has undertaken to reduce its carbon footprint.
        6. Whether the company is compliant with regulatory reporting requirements for carbon emissions (yes/no).

        Please provide the most relevant document chunks containing this information.
    """,
    'resource_usage_efficiency': """
        Find information related to the company's resource usage and efficiency. Specifically, I am looking for:
        1. Total energy consumption, provided in megawatt-hours (MWh) or gigajoules (GJ).
        2. The percentage of the total energy that comes from renewable sources.
        3. Water usage efficiency, especially water usage in cubic meters per production unit or a similar metric.
        4. Material efficiency ratio, comparing input materials to output product or waste.
        5. Waste management details, including:
          - Total waste generated (in tons).
          - Percentage of waste that is recycled.

        Please retrieve the most relevant document chunks that cover these aspects of resource usage and efficiency.
    """,
    'waste_management_pollution_control': """
        Find information about the company's waste management and pollution control efforts. Specifically, I need details on:

        1. Total waste generated by the company, measured in tons.
        2. Amount of hazardous waste generated, also in tons.
        3. The company's recycling rate, or the percentage of total waste that is recycled.
        4. Details on pollutant emissions, including:
          - NOx (nitrogen oxides) emissions in metric tons.
          - SOx (sulfur oxides) emissions in metric tons.
          - Particulate matter emissions in metric tons.

        Please retrieve the most relevant document chunks covering waste management, hazardous waste, recycling efforts, and pollution control.
    """,
    'climate_change_adaptation_risk': """
        Find information about the company's climate change adaptation efforts and risk mitigation strategies. Specifically, I need details on:

        1. The financial impact of climate-related risks on the company, measured in base currency.
        2. The amount of investment the company has made in climate risk mitigation efforts, also measured in base currency.
        3. The number of climate-related risks the company has identified and is addressing.
        4. Expenditure on infrastructure adaptation to climate change, including investments in strengthening facilities to withstand climate risks.

        Please retrieve the most relevant document chunks that address these aspects of climate change adaptation and risk mitigation.
    """,
    'employee_relations_satisfaction': """
        Find information regarding the company's employee relations and satisfaction. Specifically, I am looking for details on:

        1. Employee turnover rate, expressed as a percentage of total employees.
        2. The average tenure of employees, measured in years.
        3. Employee satisfaction score based on survey results, typically out of 100.
        4. The number of employee grievances filed within the company.
        5. The percentage of employees who are members of labor unions.

        Please provide the most relevant document chunks that cover these aspects of employee relations and satisfaction.
    """,
    'diversity_inclusion': """
        Find information about the company's diversity and inclusion efforts. Specifically, I am looking for details on:

        1. Gender diversity metrics, including:
          - Percentage of female employees in the workforce.
          - Percentage of females in leadership roles.
        2. Racial and ethnic diversity metrics, including:
          - Percentage of employees from diverse racial/ethnic backgrounds.
          - Percentage of leadership from diverse racial/ethnic backgrounds.
        3. Percentage of employees with disabilities within the company.
        4. The number of diversity training hours per employee.
        5. The pay equity ratio or any information related to the gender pay gap.

        Please provide the most relevant document chunks covering these aspects of diversity and inclusion.
    """,
    'health_safety_practices': """
        Find information about the company's health and safety practices. Specifically, I am looking for details on:

        1. Workplace injury rate, measured per 1,000 employees.
        2. Lost-time injury frequency rate (LTIFR), which indicates the number of injuries that resulted in time away from work.
        3. The number of workplace fatalities reported by the company.
        4. The percentage of employees participating in employee wellness programs.
        5. Safety training hours per employee, detailing how much safety-related training employees receive.

        Please provide the most relevant document chunks covering these aspects of health and safety practices.
    """,
    'labor_standards_human_rights': """
        Find information about the company's compliance with labor standards and human rights policies. Specifically, I am looking for details on:

        1. The percentage of employees receiving a fair wage compared to the local living wage.
        2. The number of human rights violations reported by the company.
        3. The percentage of the company's supply chain that has been audited for compliance with labor standards.
        4. The number of incidents involving child labor or forced labor reported by the company.

        Please provide the most relevant document chunks covering these aspects of labor standards and human rights compliance.
    """,
    'community_engagement_social_responsibility': """
        Find information about the company's community engagement and social responsibility initiatives. Specifically, I am looking for details on:

        1. The total investment made by the company in community projects, measured in base currency.
        2. The total number of volunteer hours contributed by employees to social or community programs.
        3. The percentage of the company's revenue that has been donated to charitable causes.
        4. The number of beneficiaries impacted by the company's social programs and community initiatives.

        Please provide the most relevant document chunks covering these aspects of community engagement and social responsibility.
    """,
    'product_safety_customer_well_being': """
        Find information about the company's product safety and customer well-being initiatives. Specifically, I am looking for details on:

        1. The number of product recalls the company has issued.
        2. The customer satisfaction score, measured by the Net Promoter Score (NPS).
        3. The number of product safety incidents that have been reported by the company.
        4. The company's compliance with product safety standards, expressed as a percentage.

        Please provide the most relevant document chunks covering these aspects of product safety and customer well-being.
    """,
    'board_structure_independence': """
        Find information about the company's board structure and independence. Specifically, I am looking for details on:

        1. The total number of board members.
        2. The percentage of independent board members.
        3. The average tenure of board members, measured in years.
        4. Gender and ethnic diversity of the board, including:
          - The percentage of female board members.
          - The percentage of board members from diverse ethnic backgrounds.

        Please provide the most relevant document chunks that cover these aspects of the company's board structure and independence.
    """,
    'executive_compensation': """
        Find information about the company's executive compensation. Specifically, I am looking for details on:

        1. The CEO-to-employee pay ratio.
        2. The total compensation for top executives, measured in base currency.
        3. The percentage of total executive compensation that is performance-based.
        4. The median employee compensation, also measured in base currency.

        Please provide the most relevant document chunks that contain these executive compensation details.
    """,
    'shareholder_rights_transparency': """
        Find information about the company's shareholder rights and transparency. Specifically, I am looking for details on:

        1. The voting rights per class of shares, including the name of the share class and the voting rights assigned to each share.
        2. The number of shareholder proposals that have been submitted.
        3. The number of shareholder meetings held by the company.
        4. The company's disclosure levels based on ESG frameworks, specifically:
          - The disclosure level based on the GRI (Global Reporting Initiative) framework.
          - The disclosure level based on the SASB (Sustainability Accounting Standards Board) framework.

        Please provide the most relevant document chunks that contain these shareholder rights and transparency details.
    """,
    'audit_risk_management': """
        Find information about the company's audit and risk management practices. Specifically, I am looking for details on:

        1. The percentage of independent members in the audit committee.
        2. The number of financial restatements or revisions made by the company.
        3. The total audit fees paid by the company, measured in base currency.
        4. The number of internal control failures or weaknesses identified during audits.

        Please provide the most relevant document chunks that cover these aspects of audit and risk management.
    """,
    'ethical_business_practices': """
        Find information about the company's ethical business practices. Specifically, I am looking for details on:

        1. The number of corruption or bribery incidents reported.
        2. The compliance rate with the company's anti-corruption policy, measured as the percentage of employees trained.
        3. The number of whistleblower reports filed.
        4. The number of violations of the company's code of ethics.

        Please provide the most relevant document chunks that cover these aspects of the company's ethical business practices.
    """,
    'succession_planning_leadership_stability': """
        Find information about the company's succession planning and leadership stability. Specifically, I am looking for details on:

        1. The number of leadership transitions (e.g., CEO, CFO) that have occurred.
        2. The average tenure of senior executives, measured in years.
        3. The number of internal promotions to executive roles within the company.
        4. The number of external hires for executive roles.

        Please provide the most relevant document chunks that cover these aspects of succession planning and leadership stability.
    """,
    'stakeholder_engagement': """
        Find information about the company's stakeholder engagement efforts. Specifically, I am looking for details on:

        1. The number of stakeholder meetings held by the company.
        2. The percentage of stakeholders consulted during decision-making processes.
        3. The stakeholder engagement survey satisfaction score, measured out of 100.
        4. The number of stakeholder feedback comments disclosed by the company.

        Please provide the most relevant document chunks that cover these aspects of stakeholder engagement.
    """,
    'environmental_impact': """
        Find information about the environmental impact of the company's activities. Specifically, I am looking for details on:

        1. The total carbon footprint of the company, measured in metric tons.
        2. The total energy consumption of the company, measured in gigawatt-hours (GWh) or joules.
        3. The total water usage by the company, measured in cubic meters.
        4. Air pollutants emitted by the company, including:
          - SOx emissions (sulfur oxides), measured in metric tons.
          - NOx emissions (nitrogen oxides), measured in metric tons.
          - Particulate matter emissions, measured in metric tons.
        5. The total hazardous waste generated by the company, measured in metric tons.
        6. The total non-hazardous waste generated by the company, measured in metric tons.
        7. A summary of any biodiversity impacts, such as deforestation or impacts on protected areas.

        Please provide the most relevant document chunks that cover these aspects of the company's environmental impact.
    """
    
}

company_info_query = {
    'company_history': """
        Retrieve detailed information about the history and evolution of the company, starting from its foundation and key 
        milestones achieved over the years. Include significant events such as the establishment, initial public offerings (IPO),
        mergers and acquisitions, major expansions, and strategic shifts that contributed to the company’s growth. Highlight the
        company’s presence in domestic and international markets, detailing key regions where it operates and its role in industry 
        leadership. Focus on innovations, product or service expansions, and notable transformations that have helped the company
        adapt to market dynamics. Also include recognitions, awards, and achievements that emphasize the company’s contribution 
        to its industry, such as leadership in sustainability, customer service, market share, or technological advancements. 
        Provide details on the company’s long-term strategy and its influence across sectors.
    """,
    'products_and_services':"""
        Provide a detailed description of the company’s products and services, focusing on the core offerings, solutions, and
        business verticals. Include how the company supports its clients across different industries by offering a diverse range 
        of services, such as consulting, manufacturing, technology, finance, or any other industry-specific solutions. Highlight 
        key areas of innovation, including the adoption of emerging technologies, process improvements, or new product development. 
        If applicable, mention any platforms, solutions, or products that are central to the company’s strategy. Additionally, include 
        information about the company's commitment to sustainability and integration of environmental, social, and governance (ESG) 
        factors into its operations and services. Ensure that the description reflects the company's global presence, its impact on various 
        markets, and how its products and services enable clients to achieve their goals in a competitive and evolving business landscape.
    """,
    'awards_and_recognition':"""
        Provide a detailed summary of the company’s awards and recognitions, highlighting major accolades the company has received over 
        the years. Include specific mentions of industry awards, rankings, or any prestigious recognitions from institutions, media, or 
        governing bodies. Focus on the company’s achievements in areas such as business performance, innovation, sustainability, corporate 
        governance, customer service, and other relevant domains. Additionally, include any distinctions in terms of global rankings, leadership 
        in the industry, or other significant accomplishments that emphasize the company’s reputation and standing in its sector.
    """,
    'company_name': """
        Find the full legal name of the company, including any subsidiaries or affiliated entities. This information is essential for
        identifying the company accurately and ensuring that the details provided are specific to the correct organization.
    """
}